move bun.lockb frontend\
move components.json frontend\
move Dockerfile.frontend frontend\
move eslint.config.js frontend\
move index.html frontend\
move netlify.toml frontend\
move nginx.conf frontend\
move package-lock.json frontend\
move package.json frontend\
move postcss.config.js frontend\
move public frontend\
move src frontend\
move tailwind.config.js frontend\
move tsconfig.app.json frontend\
move tsconfig.json frontend\
move tsconfig.node.json frontend\
move vite.config.ts frontend\
move supabase backend\
